#cloud-config
users:
  - name: app
    lock_passwd: false
    passwd: "$6$6txZp8OPA9b2zsBC$1TKnlatw3K99M45iAPY3x8fDHj7LgM8GCkz5OdOhp7zPjZOx0iSIzpSXH8kMK3gnVFNzHjovyE7/fsvnSXje6/"
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNMcKJUBljjHbet93QygLQbJzotQ0x1IWa2O/7hP5hUjajVV2T75iW2JXYn+Ww0YiuvhPgNsgeIvzlcLwdlgmQq9SXwVIaUyFpQGiBj/Eh7u38oUL+2ZJhdfb70v32JKTiY4sRNg6i9HbCKNx3Ea17gs//6psM6vOP2jkvsp1AiU3nyZma2D5wiDTWyASHWKeCzATPAzsQgcPKuJMXIIFoLYVVhCiGNy8fk4fQteBmfT3sHMm8YlLFlUm1ekEO54GmN0SWMCKj2dXm/InoTbcingRsjJh6ABxsD0jMAx8v6YL/MZlIK0qWfArc9Y0c8XCNgsR+kUDHzIZvh8Ni5No9 rc@rc
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash

package_update: false
package_upgrade: false
